async (page) => {
  const assert=(v,m)=>{if(!v)throw new Error(m);};
  const key='marcoIeltsListening.v1';
  await page.goto('http://127.0.0.1:4173/');
  await page.evaluate(key=>localStorage.removeItem(key),key);
  await page.reload();
  await page.locator('#vocab-new').waitFor();
  const read=()=>page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
  const initial=await read();
  const total=Object.values(initial.errorWords).filter(r=>r.isErrorWord).length;
  assert(total===236,'static true errors not fully migrated');
  await page.locator('#home-more summary').click();
  await page.locator('#error-library').click();
  assert(await page.locator('.error-library-card').count()===20,'archive not paginated');
  assert((await page.locator('[data-error-filter=all]').innerText()).includes(String(total)),'all count incorrect');
  const id=await page.locator('[data-pardon]').first().getAttribute('data-pardon');
  const old=initial.errorWords[id];
  await page.locator(`[data-star="${id}"]`).click();
  await page.locator(`[data-pardon="${id}"]`).click();
  const pardoned=(await read()).errorWords[id];
  assert(pardoned.isErrorWord && pardoned.pardoned,'pardon removed identity');
  assert(pardoned.wrongCount===old.wrongCount,'pardon changed history count');
  assert(JSON.stringify(pardoned.sources)===JSON.stringify(old.sources),'pardon changed sources');
  assert((await read()).starred[id],'pardon removed star');
  assert(!(await read()).vocabErrorDaily.queue.some(e=>e.key===id+':vocab'),'pardon still in active queue');
  await page.locator('[data-error-filter=pardoned]').click();
  assert(await page.locator('.error-library-card').count()===1,'pardoned group wrong');
  await page.locator(`[data-star="${id}"]`).click();
  assert(!(await read()).starred[id],'cannot unstar pardoned word');
  await page.locator(`[data-star="${id}"]`).click();
  await page.locator('[data-error-filter=all]').click();
  const term=await page.locator(`[data-star="${id}"]`).locator('xpath=ancestor::article').locator('h2').innerText();
  await page.locator('#error-search').fill(term);
  assert(await page.locator('.error-library-card').count()>=1,'search lost matching word');
  const layouts=[];
  for(const viewport of [{width:390,height:844},{width:1440,height:900},{width:320,height:568}]) {
    await page.setViewportSize(viewport);
    const width=await page.evaluate(()=>document.documentElement.scrollWidth);
    assert(width===viewport.width,'archive horizontal overflow');
    layouts.push(viewport);
  }
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'output/audit-archive-390.png'});
  await page.locator('#error-search').fill('no-match-test-word');
  assert(await page.locator('.empty-card').count()===1,'search empty state missing');
  await page.locator('#library-back').click();
  assert((await page.locator('#error-counts').innerText()).includes(`错词 ${total} · 活跃 ${total-1} · 已赦免 1`),'home archive counts diverge');
  await page.reload();
  await page.locator('#vocab-new').waitFor();
  assert((await read()).starred[id] && (await read()).errorWords[id].isErrorWord,'archive/star lost after reload');
  await page.locator('#vocab-errors').click();
  assert(await page.locator('.meaning').count()===0,'error training leaks answer');
  const activeId=(await read()).vocabErrorDaily.queue[0].key.replace(/:vocab$/,'');
  await page.locator('#vocab-known').click();
  await page.locator('.session-star').click();
  assert((await read()).starred[activeId],'native reveal star does not save');
  assert((await read()).errorWords[activeId].isErrorWord,'correct answer removed error identity');
  return {ok:true,total,active:total-1,pardoned:1,layouts,cases:['pardon-history','pardon-star','all-counts','search','pagination','refresh','error-reveal-star','pass-identity']};
}
